[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
felt-platform = { path = "../crates/felt-platform" }
felt-ui = { path = "../crates/felt-ui" }
vello = "0.3.0"
winit = "0.29"
log = "0.4"
env_logger = "0.10"
